version: "3.9"

services:
    app:
        container_name: gis
        image: gis
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8084:8080"