version: "3.9"

services:
    oceanops-gis:
        container_name: oceanops-gis
        image: oceanops-gis
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - "8084:8080"